export const FETCH_ARTICLES  = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const FILTER_ARTICLE_SUCCESS = 'FILTER_ARTICLE_SUCCESS';
export const FILTER_ARTICLE_ERROR = 'FILTER_ARTICLE_ERROR';
export const GET_ARTICLE = 'GET_ARTICLE';